# .github/release.yml

changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - dependabot
  categories:
    - title: 🎉 New Features
      labels:
        - feature
        - enhancement
    - title: 🐛 Bug Fixes
      labels:
        - bug
        - bugfix
        - fix
    - title: 🧹 Maintenance
      labels:
        - chore
        - dependencies
    - title: 📚 Documentation
      labels:
        - documentation
        - docs
    - title: ⚡ Performance
      labels:
        - performance
        - optimization
    - title: Other Changes
      labels:
        - "*"