modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="etherealmind"
version="3.0.0"
displayName="Ethereal Mind"
logoFile="etherealmind.png"
credits="AstroLabs Development Team"
authors="AstroLabs"
description='''
Ethereal Mind: Natural Language AI Companion
Featuring COSMO - Your Intelligent Cosmic Companion

COSMO is an advanced AI entity that understands natural language commands and grows with you.
Chat with COSMO naturally, watch them respond with speech bubbles and emotes, and enjoy
a truly interactive companion experience.

Key Features:
• Natural Language Commands: "COSMO, follow me" or "COSMO, bring me food"
• Speech Bubbles & Emotes: Visual feedback with personality
• Smart Item Management: Fetch by category (food, tools, armor, etc.)
• Environmental Awareness: Comments on weather, time, and surroundings
• Combat Assistance (Level 5+): Healing, enemy marking, and protection
• Resource Gathering: Auto-collect items and harvest crops
• Progressive Leveling System (1-10) with unlockable abilities
• Massive Storage: 432-3,456 slots based on level
'''

[[dependencies.etherealmind]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.etherealmind]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"