name: Publish to Mod Platforms

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Build mod
      run: ./gradlew clean build
    
    - name: Get release info
      id: release
      run: |
        echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
        echo "MC_VERSION=1.20.1" >> $GITHUB_OUTPUT
    
    # Publish to CurseForge
    - name: Publish to CurseForge
      if: env.CURSEFORGE_TOKEN != ''
      env:
        CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
      run: |
        ./gradlew curseforge
      continue-on-error: true
    
    # Publish to Modrinth
    - name: Publish to Modrinth
      if: env.MODRINTH_TOKEN != ''
      uses: Kir-Antipov/mc-publish@v3.2
      with:
        modrinth-id: your-mod-id  # Replace with your Modrinth project ID
        modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
        modrinth-featured: true
        
        files: |
          build/libs/etherealmind-${{ steps.release.outputs.MC_VERSION }}-${{ steps.release.outputs.VERSION }}.jar
        
        name: EtherealMind ${{ steps.release.outputs.VERSION }}
        version: ${{ steps.release.outputs.VERSION }}
        version-type: release
        
        changelog-file: CHANGELOG.md
        
        loaders: |
          forge
        
        game-versions: |
          1.20.1
        
        dependencies: |
          geckolib-forge(required)
        
        java: |
          17