name: Upload Release JAR

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag (e.g., v3.0.0)'
        required: true
        default: 'v3.0.0'

jobs:
  upload-jar:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.release_tag }}
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    
    - name: Extract version from tag
      id: version
      run: echo "VERSION=$(echo '${{ github.event.inputs.release_tag }}' | sed 's/^v//')" >> $GITHUB_OUTPUT
    
    - name: Build with Gradle
      run: ./gradlew build
    
    - name: Find built JAR
      id: find_jar
      run: |
        JAR_FILE=$(find build/libs -name "*.jar" -not -name "*-sources.jar" | head -1)
        echo "Found JAR: $JAR_FILE"
        echo "JAR_PATH=$JAR_FILE" >> $GITHUB_OUTPUT
        echo "JAR_NAME=$(basename $JAR_FILE)" >> $GITHUB_OUTPUT
    
    - name: Upload JAR to release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release upload ${{ github.event.inputs.release_tag }} \
          "${{ steps.find_jar.outputs.JAR_PATH }}" \
          --clobber \
          --repo ${{ github.repository }}